# Generated by Django 3.1.1 on 2023-02-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstudent',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
    ]
