# Generated by Django 3.1.1 on 2023-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_leavereportstudent_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='innumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
